In [566]:
from mido import MidiFile

In [567]:
import os
import py_midicsv
import pandas as pd


for filename in os.listdir('data'):
    csv = py_midicsv.midi_to_csv("data/" + filename)

#     for line in csv:
#         print(line)
    Ans=[]
    for k in csv:
        L=k.strip().split(", ")
        Ans.append(L)
    df = pd.DataFrame(Ans)
    df.to_csv('data/'+filename+".csv")
    df.head(10)

TypeError: ('Bad header in MIDI file.', b',0,1')

In [658]:
import pandas as pd
L=[]
for filename in os.listdir('csv'):
    print(filename)
    data = pd.read_csv('csv/'+filename)
    data =data[data['2'] == "Note_on_c"]
    
    L.append(data)
len(L)

1.mid.csv
2.mid.csv
3.mid.csv
4.mid.csv
5.mid.csv
6.mid.csv

6

1#

In [659]:
last_time = -1
LL =[]

for i in range(6):
    print(last_time)
    df1 = L[i].copy()
    df1['1'] = df1['1']/96 + int(last_time) +1
    df1 = df1[['1','4','5']]
    LL.append(df1)
    last_time = (df1.tail(1)['1'])
    print(df1)

-1
          1     4      5
7      0.00  76.0  112.0
9      0.75  74.0  112.0
11     1.50  72.0  112.0
13     2.25  71.0  112.0
15     3.00  69.0  112.0
..      ...   ...    ...
957  359.50  76.0  126.0
959  360.00  71.0  126.0
961  360.50  72.0  126.0
963  361.00  69.0  127.0
965  362.50  81.0  127.0

[480 rows x 3 columns]
965    362.5
Name: 1, dtype: float64
            1     4     5
8    363.0625  69.0  80.0
10   363.5625  69.0  80.0
12   364.0625  81.0  80.0
14   365.0625  76.0  80.0
16   366.5625  75.0  80.0
..        ...   ...   ...
770  808.5625  72.0  96.0
772  809.5625  69.0  96.0
774  810.0625  69.0  96.0
776  810.5625  69.0  96.0
778  811.0625  69.0  96.0

[386 rows x 3 columns]
778    811.0625
Name: 1, dtype: float64
                1     4     5
7      812.510417  60.0  80.0
9      813.010417  64.0  80.0
11     813.510417  64.0  80.0
13     814.010417  60.0  80.0
15     814.510417  60.0  80.0
...           ...   ...   ...
1133  1163.010417  71.0  80.0
1135  1163.510417  72.0  80.0
1137  1164.010417  71.0  80.0
1139  1164.510417  72.0  80.0
1141  1165.010417  69.0  80.0

[568 rows x 3 columns]
1141    1165.010417
Name: 1, dtype: float64
          1     4     5
8    1166.0  69.0  80.0
10   1166.5  69.0  80.0
12   1167.0  81.0  80.0
14   1168.0  76.0  80.0
16   1169.5  75.0  80.0
..      ...   ...   ...
770  1611.5  72.0  96.0
772  1612.5  69.0  96.0
774  1613.0  69.0  96.0
776  1613.5  69.0  96.0
778  1614.0  69.0  96.0

[386 rows x 3 columns]
778    1614.0
Name: 1, dtype: float64
          1     4     5
8    1615.0  81.0  80.0
10   1616.5  79.0  80.0
12   1617.5  76.0  80.0
14   1618.0  74.0  80.0
16   1619.0  69.0  80.0
..      ...   ...   ...
402  1896.0  67.0  80.0
404  1897.0  70.0  80.0
406  1897.5  71.0  80.0
408  1898.5  72.0  80.0
410  1901.0  60.0  80.0

[202 rows x 3 columns]
410    1901.0
Name: 1, dtype: float64
           1     4     5
8    1902.00  64.0  96.0
10   1902.50  66.0  96.0
12   1902.75  68.0  96.0
14   1903.00  69.0  96.0
16   1903.50  69.0  96.0
..       ...   ...   ...
624  2059.00  76.0  96.0
626  2059.50  74.0  96.0
628  2060.00  76.0  96.0
630  2060.50  80.0  96.0
632  2061.00  81.0  96.0

[313 rows x 3 columns]

In [650]:
column_names = ["1", "4", "5"]
df2 = pd.DataFrame(columns = column_names)
for k in LL:
    df3 = pd.concat([df2, k])
    df2 = df3
df3.tail(20)

          1     4     5
372   983.0  70.0  80.0
374   983.5  71.0  80.0
376   984.5  72.0  80.0
378   986.0  70.0  80.0
380   987.0  72.0  80.0
382   988.0  73.0  80.0
384   989.0  72.0  80.0
386   990.0  67.0  80.0
388   991.0  70.0  80.0
390   991.5  71.0  80.0
392   992.5  72.0  80.0
394   994.0  67.0  80.0
396   995.0  70.0  80.0
398   996.0  71.0  80.0
400   997.0  72.0  80.0
402   998.0  67.0  80.0
404   999.0  70.0  80.0
406   999.5  71.0  80.0
408  1000.5  72.0  80.0
410  1003.0  60.0  80.0

In [660]:
result = pd.concat(LL)
result.to_csv('songs.csv')

In [10]:
result

          1     4     5
7      16.0  61.0  80.0
9      18.0  59.0  80.0
11     20.0  57.0  80.0
13     22.0  56.0  80.0
15     24.0  54.0  80.0
..      ...   ...   ...
367  1427.0  59.0  80.0
369  1428.0  61.0  80.0
371  1429.0  57.0  80.0
373  1430.0  54.0  80.0
375  1431.0  54.0  80.0

[1671 rows x 3 columns]

In [652]:
import pandas as pd
L=[]
for filename in os.listdir('csv2'):
    print(filename)
    data = pd.read_csv('csv2/'+filename)
    data =data[data['2'] == "Note_on_c"]
    
    L.append(data)
L[0].tail(40)

start.mid.csv

     Unnamed: 0  0     1          2  3     4     5   6
96           96  2  3216  Note_on_c  0  61.0  80.0 NaN
98           98  2  3264  Note_on_c  0  69.0  80.0 NaN
100         100  2  3312  Note_on_c  0  66.0  80.0 NaN
102         102  2  3408  Note_on_c  0  64.0  80.0 NaN
104         104  2  3504  Note_on_c  0  66.0  80.0 NaN
106         106  2  3600  Note_on_c  0  61.0  80.0 NaN
108         108  2  3648  Note_on_c  0  64.0  80.0 NaN
110         110  2  3696  Note_on_c  0  61.0  80.0 NaN
112         112  2  3744  Note_on_c  0  66.0  80.0 NaN
114         114  2  3792  Note_on_c  0  61.0  80.0 NaN
116         116  2  3840  Note_on_c  0  69.0  80.0 NaN
118         118  2  3936  Note_on_c  0  66.0  80.0 NaN
120         120  2  4032  Note_on_c  0  64.0  80.0 NaN
122         122  2  4080  Note_on_c  0  66.0  80.0 NaN
124         124  2  4176  Note_on_c  0  69.0  80.0 NaN
126         126  2  4272  Note_on_c  0  71.0  80.0 NaN
128         128  2  4368  Note_on_c  0  64.0  80.0 NaN
130         130  2  4416  Note_on_c  0  66.0  80.0 NaN
132         132  2  4464  Note_on_c  0  69.0  80.0 NaN
134         134  2  4512  Note_on_c  0  71.0  80.0 NaN
136         136  2  4560  Note_on_c  0  73.0  80.0 NaN
138         138  2  4573  Note_on_c  0  74.0  80.0 NaN
140         140  2  4608  Note_on_c  0  73.0  80.0 NaN
142         142  2  4656  Note_on_c  0  69.0  80.0 NaN
144         144  2  4704  Note_on_c  0  66.0  80.0 NaN
146         146  2  4752  Note_on_c  0  64.0  80.0 NaN
148         148  2  4800  Note_on_c  0  66.0  80.0 NaN
150         150  2  4848  Note_on_c  0  69.0  80.0 NaN
152         152  2  4944  Note_on_c  0  73.0  80.0 NaN
154         154  2  5040  Note_on_c  0  71.0  80.0 NaN
156         156  2  5136  Note_on_c  0  69.0  80.0 NaN
158         158  2  5232  Note_on_c  0  66.0  80.0 NaN
160         160  2  5328  Note_on_c  0  76.0  80.0 NaN
162         162  2  5340  Note_on_c  0  77.0  80.0 NaN
164         164  2  5352  Note_on_c  0  78.0  80.0 NaN
166         166  2  5616  Note_on_c  0  76.0  80.0 NaN
168         168  2  5712  Note_on_c  0  73.0  80.0 NaN
170         170  2  5856  Note_on_c  0  73.0  67.0 NaN
172         172  2  5952  Note_on_c  0  73.0  58.0 NaN
174         174  2  6048  Note_on_c  0  73.0  49.0 NaN

In [10]:
last_time = -1
LL =[]

for i in range(1):
    print(last_time)
    df1 = L[2*i].copy()
    df1['1'] = df1['1']/96 + int(last_time) +1
    df1 = df1[['1','4','5']]
    LL.append(df1)
    last_time = (df1.tail(1)['1'])
    print(df1.head(10))

-1
      1     4     5
8   0.0  64.0  80.0
10  1.0  66.0  80.0
12  1.5  61.0  80.0
14  2.0  69.0  80.0
16  2.5  66.0  80.0
18  3.5  64.0  80.0
20  4.5  66.0  80.0
22  5.5  61.0  80.0
24  6.0  64.0  80.0
26  6.5  61.0  80.0

In [653]:
result = pd.concat(LL)
result.to_csv('songs.csv')
result

           1     4      5
7       0.00  76.0  112.0
9       0.75  74.0  112.0
11      1.50  72.0  112.0
13      2.25  71.0  112.0
15      3.00  69.0  112.0
..       ...   ...    ...
402   998.00  67.0   80.0
404   999.00  70.0   80.0
406   999.50  71.0   80.0
408  1000.50  72.0   80.0
410  1003.00  60.0   80.0

[1250 rows x 3 columns]

In [11]:
import tensorflow as tf

In [20]:
result.shape

(1671, 3)

In [663]:
# result.iloc[:20].shape
# x_train =  [result.iloc[x:x+20] for x in range(0,1640)] 
# y_train =  [result.iloc[x] for x in range(21,1640)] 
# result.iloc[:20].shape
x_train = numpy.array ( [result.iloc[x:x+10].to_numpy() for x in range(0,2300)] )
y_train = numpy.array( [result.iloc[x+11].to_numpy() for x in range(0,2300)] )

In [580]:
import numpy

In [639]:
x_train[0][0]

array([16., 61., 80.])

In [378]:
y_train[100]

array([125.,  62.,  80.])

In [367]:
# result.hea

In [589]:
for x,y in zip(x_train,y_train):
    print(y_train.shape)
    break

AttributeError: 'list' object has no attribute 'shape'

In [664]:
def get_feedforward():
    input1 = tf.keras.layers.Input(shape=(10,3))
    x = tf.keras.layers.Dense(100, activation='relu')(input1)
    x = tf.keras.layers.Dense(100, activation='relu')(x)
    x = tf.keras.layers.Dense(100, activation='relu')(x)
    out = tf.keras.layers.Dense(3, activation='relu')(x)
    
    model = tf.keras.models.Model(inputs=input1, outputs=out)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(lr=1e-4),
        loss='mean_squared_error',
        metrics=['acc']
    )
    return model

In [581]:
model = get_feedforward()
model.summary()

Model: "model_53"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_57 (InputLayer)        [(None, 20, 3)]           0
_________________________________________________________________
dense_294 (Dense)            (None, 20, 100)           400
_________________________________________________________________
dense_295 (Dense)            (None, 20, 100)           10100
_________________________________________________________________
dense_296 (Dense)            (None, 20, 100)           10100
_________________________________________________________________
dense_297 (Dense)            (None, 20, 3)             303
=================================================================
Total params: 20,903
Trainable params: 20,903
Non-trainable params: 0
_________________________________________________________________

In [383]:
model.fit(x_train, y_train, epochs=3, batch_size=1, verbose=1)

RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.

In [382]:
y_pred = model.predict(numpy.array([result.iloc[-20:].to_numpy()]))
arr = lambda i: round(i)
# cleaned_y = arr(y_pred)
y_pred = numpy.round(y_pred*4) / 4
y_pred
# cleaned_y
# x_train.shape

array([[480.25,   0.  ,   0.  ]], dtype=float32)

In [308]:
a = lambda x : print(x[0])
y_pred[0]

array([[66.75,  0.  ,  0.  ],
       [66.75,  0.  ,  0.  ],
       [66.75,  0.  ,  0.  ],
       [66.75,  0.  ,  0.  ],
       [66.75,  0.  ,  0.  ],
       [67.  ,  0.  ,  0.  ],
       [67.  ,  0.  ,  0.  ],
       [67.  ,  0.  ,  0.  ],
       [67.25,  0.  ,  0.  ],
       [67.  ,  0.  ,  0.  ],
       [67.25,  0.  ,  0.  ],
       [67.25,  0.  ,  0.  ],
       [67.25,  0.  ,  0.  ],
       [67.25,  0.  ,  0.  ],
       [67.25,  0.  ,  0.  ],
       [67.25,  0.  ,  0.  ],
       [67.25,  0.  ,  0.  ],
       [67.5 ,  0.  ,  0.  ],
       [67.5 ,  0.  ,  0.  ],
       [67.75,  0.  ,  0.  ]], dtype=float32)

In [309]:
numpy.savetxt("namkang.csv", y_pred[0], delimiter=",")

In [1]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(128, 96)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    

    tf.keras.layers.Dense(3, activation='relu')
])
model.compile(
        optimizer=tf.keras.optimizers.Adam(lr=1e-4),
        loss='mean_squared_error',
        metrics=['acc']
    )

NameError: name 'tf' is not defined

In [670]:
model.fit(x_train, y_train, epochs=100, batch_size=10,verbose=1)

Epoch 1/100
2300/2300 [==============================] - 1s 338us/sample - loss: 255212.7159 - acc: 0.5070
Epoch 2/100
2300/2300 [==============================] - 0s 205us/sample - loss: 51.1664 - acc: 0.9970
Epoch 3/100
2300/2300 [==============================] - 0s 201us/sample - loss: 31.8550 - acc: 0.9983
Epoch 4/100
2300/2300 [==============================] - 0s 203us/sample - loss: 28.7739 - acc: 0.9978
Epoch 5/100
2300/2300 [==============================] - 0s 199us/sample - loss: 27.7297 - acc: 0.9978
Epoch 6/100
2300/2300 [==============================] - 0s 204us/sample - loss: 27.7475 - acc: 0.9983
Epoch 7/100
2300/2300 [==============================] - 1s 222us/sample - loss: 27.2148 - acc: 0.9987
Epoch 8/100
2300/2300 [==============================] - 0s 202us/sample - loss: 27.1242 - acc: 0.9991
Epoch 9/100
2300/2300 [==============================] - 0s 201us/sample - loss: 27.6354 - acc: 0.9983
Epoch 10/100
2300/2300 [==============================] - 0s 210us/sample - loss: 28.2467 - acc: 0.9991
Epoch 11/100
2300/2300 [==============================] - 0s 214us/sample - loss: 25.8194 - acc: 0.9983
Epoch 12/100
2300/2300 [==============================] - 1s 231us/sample - loss: 26.2547 - acc: 0.9983
Epoch 13/100
2300/2300 [==============================] - 1s 223us/sample - loss: 25.4097 - acc: 0.9983
Epoch 14/100
2300/2300 [==============================] - 1s 218us/sample - loss: 25.3972 - acc: 0.9987
Epoch 15/100
2300/2300 [==============================] - 1s 241us/sample - loss: 25.2811 - acc: 0.9987
Epoch 16/100
2300/2300 [==============================] - 1s 224us/sample - loss: 25.1434 - acc: 0.9978
Epoch 17/100
2300/2300 [==============================] - 0s 207us/sample - loss: 27.1541 - acc: 0.9987
Epoch 18/100
2300/2300 [==============================] - 0s 211us/sample - loss: 25.4414 - acc: 0.9987
Epoch 19/100
2300/2300 [==============================] - 0s 206us/sample - loss: 26.1173 - acc: 0.9983
Epoch 20/100
2300/2300 [==============================] - 0s 210us/sample - loss: 25.1441 - acc: 0.9991
Epoch 21/100
2300/2300 [==============================] - 0s 203us/sample - loss: 22.4527 - acc: 0.9983
Epoch 22/100
2300/2300 [==============================] - 0s 208us/sample - loss: 24.4019 - acc: 0.9983
Epoch 23/100
2300/2300 [==============================] - 1s 222us/sample - loss: 23.8584 - acc: 0.9978
Epoch 24/100
2300/2300 [==============================] - 0s 213us/sample - loss: 27.4732 - acc: 0.9983
Epoch 25/100
2300/2300 [==============================] - 0s 212us/sample - loss: 24.3784 - acc: 0.9978
Epoch 26/100
2300/2300 [==============================] - 1s 238us/sample - loss: 22.1692 - acc: 0.9987
Epoch 27/100
2300/2300 [==============================] - 0s 212us/sample - loss: 27.1377 - acc: 0.9983
Epoch 28/100
2300/2300 [==============================] - 0s 216us/sample - loss: 27.5847 - acc: 0.9978
Epoch 29/100
2300/2300 [==============================] - 0s 212us/sample - loss: 23.2491 - acc: 0.9983 - loss: 25.4440
Epoch 30/100
2300/2300 [==============================] - 0s 216us/sample - loss: 23.8423 - acc: 0.9978
Epoch 31/100
2300/2300 [==============================] - 1s 237us/sample - loss: 25.4152 - acc: 0.9970 - loss: 18.
Epoch 32/100
2300/2300 [==============================] - ETA: 0s - loss: 22.7658 - acc: 0.9982 ETA: 0s - loss: 17. - 0s 212us/sample - loss: 22.9946 - acc: 0.9983
Epoch 33/100
2300/2300 [==============================] - 0s 215us/sample - loss: 23.5495 - acc: 0.9987
Epoch 34/100
2300/2300 [==============================] - 0s 215us/sample - loss: 21.3074 - acc: 0.9974
Epoch 35/100
2300/2300 [==============================] - 0s 213us/sample - loss: 22.4823 - acc: 0.9974
Epoch 36/100
2300/2300 [==============================] - 1s 218us/sample - loss: 22.6920 - acc: 0.9978
Epoch 37/100
2300/2300 [==============================] - 1s 221us/sample - loss: 22.2584 - acc: 0.9987
Epoch 38/100
2300/2300 [==============================] - 0s 212us/sample - loss: 21.3296 - acc: 0.9991
Epoch 39/100
2300/2300 [==============================] - 1s 240us/sample - loss: 21.3392 - acc: 0.9987
Epoch 40/100
2300/2300 [==============================] - 0s 215us/sample - loss: 23.9620 - acc: 0.9983
Epoch 41/100
2300/2300 [==============================] - 0s 213us/sample - loss: 21.7338 - acc: 0.9983
Epoch 42/100
2300/2300 [==============================] - 0s 210us/sample - loss: 21.3438 - acc: 0.9983
Epoch 43/100
2300/2300 [==============================] - 0s 207us/sample - loss: 23.1304 - acc: 0.9978
Epoch 44/100
2300/2300 [==============================] - 0s 217us/sample - loss: 21.0086 - acc: 0.9983
Epoch 45/100
2300/2300 [==============================] - 1s 230us/sample - loss: 22.9258 - acc: 0.9991
Epoch 46/100
2300/2300 [==============================] - 1s 228us/sample - loss: 22.1189 - acc: 0.9978
Epoch 47/100
2300/2300 [==============================] - 1s 250us/sample - loss: 23.4769 - acc: 0.9983
Epoch 48/100
2300/2300 [==============================] - 1s 234us/sample - loss: 19.2320 - acc: 0.9983
Epoch 49/100
2300/2300 [==============================] - 1s 228us/sample - loss: 21.9275 - acc: 0.9978
Epoch 50/100
2300/2300 [==============================] - 1s 225us/sample - loss: 23.6980 - acc: 0.9987
Epoch 51/100
2300/2300 [==============================] - 0s 217us/sample - loss: 23.4898 - acc: 0.9983
Epoch 52/100
2300/2300 [==============================] - 0s 212us/sample - loss: 21.1482 - acc: 0.9987
Epoch 53/100
2300/2300 [==============================] - 1s 230us/sample - loss: 20.2768 - acc: 0.9983
Epoch 54/100
2300/2300 [==============================] - 1s 222us/sample - loss: 20.9389 - acc: 0.9983
Epoch 55/100
2300/2300 [==============================] - 1s 257us/sample - loss: 22.7257 - acc: 0.9987
Epoch 56/100
2300/2300 [==============================] - 1s 223us/sample - loss: 19.1521 - acc: 0.9978
Epoch 57/100
2300/2300 [==============================] - 1s 219us/sample - loss: 19.8914 - acc: 0.9987
Epoch 58/100
2300/2300 [==============================] - 0s 215us/sample - loss: 20.3522 - acc: 0.9983
Epoch 59/100
2300/2300 [==============================] - 1s 246us/sample - loss: 21.5237 - acc: 0.9991
Epoch 60/100
2300/2300 [==============================] - 1s 240us/sample - loss: 19.4276 - acc: 0.9983
Epoch 61/100
2300/2300 [==============================] - 1s 224us/sample - loss: 21.1602 - acc: 0.9983
Epoch 62/100
2300/2300 [==============================] - 1s 244us/sample - loss: 20.2464 - acc: 0.9983
Epoch 63/100
2300/2300 [==============================] - 0s 217us/sample - loss: 20.8425 - acc: 0.9978
Epoch 64/100
2300/2300 [==============================] - 1s 218us/sample - loss: 19.7748 - acc: 0.9987
Epoch 65/100
2300/2300 [==============================] - 1s 246us/sample - loss: 20.3397 - acc: 0.9987 - loss: 16.17
Epoch 66/100
2300/2300 [==============================] - 1s 226us/sample - loss: 19.6516 - acc: 0.9978
Epoch 67/100
2300/2300 [==============================] - 1s 234us/sample - loss: 22.0137 - acc: 0.9987
Epoch 68/100
2300/2300 [==============================] - 1s 247us/sample - loss: 20.1403 - acc: 0.9983
Epoch 69/100
2300/2300 [==============================] - 1s 238us/sample - loss: 21.8299 - acc: 0.9987
Epoch 70/100
2300/2300 [==============================] - 1s 246us/sample - loss: 25.7863 - acc: 0.9987
Epoch 71/100
2300/2300 [==============================] - 0s 208us/sample - loss: 18.3892 - acc: 0.9987
Epoch 72/100
2300/2300 [==============================] - 1s 241us/sample - loss: 19.4732 - acc: 0.9991
Epoch 73/100
2300/2300 [==============================] - 0s 213us/sample - loss: 19.6147 - acc: 0.9987
Epoch 74/100
2300/2300 [==============================] - 1s 220us/sample - loss: 17.4285 - acc: 0.9978
Epoch 75/100
2300/2300 [==============================] - 1s 226us/sample - loss: 18.7752 - acc: 0.9983
Epoch 76/100
2300/2300 [==============================] - 1s 229us/sample - loss: 18.7171 - acc: 0.9991
Epoch 77/100
2300/2300 [==============================] - 1s 232us/sample - loss: 21.3330 - acc: 0.9987
Epoch 78/100
2300/2300 [==============================] - 0s 206us/sample - loss: 19.1063 - acc: 0.9983
Epoch 79/100
2300/2300 [==============================] - 0s 203us/sample - loss: 18.1442 - acc: 0.9987
Epoch 80/100
2300/2300 [==============================] - 0s 200us/sample - loss: 20.3761 - acc: 0.9987
Epoch 81/100
2300/2300 [==============================] - 0s 216us/sample - loss: 18.1590 - acc: 0.9983
Epoch 82/100
2300/2300 [==============================] - 1s 222us/sample - loss: 20.3480 - acc: 0.9978
Epoch 83/100
2300/2300 [==============================] - 0s 214us/sample - loss: 18.0888 - acc: 0.9978
Epoch 84/100
2300/2300 [==============================] - 0s 213us/sample - loss: 21.7125 - acc: 0.9983 - loss: 18.
Epoch 85/100
2300/2300 [==============================] - 1s 231us/sample - loss: 20.1043 - acc: 0.9983
Epoch 86/100
2300/2300 [==============================] - 0s 216us/sample - loss: 19.0614 - acc: 0.9987
Epoch 87/100
2300/2300 [==============================] - 0s 210us/sample - loss: 21.2873 - acc: 0.9983
Epoch 88/100
2300/2300 [==============================] - 0s 210us/sample - loss: 18.2426 - acc: 0.9987 - loss: 20.1728 - acc
Epoch 89/100
2300/2300 [==============================] - 1s 218us/sample - loss: 20.3548 - acc: 0.9987
Epoch 90/100
2300/2300 [==============================] - 0s 210us/sample - loss: 16.8551 - acc: 0.9978
Epoch 91/100
2300/2300 [==============================] - 0s 213us/sample - loss: 18.1057 - acc: 0.9991
Epoch 92/100
2300/2300 [==============================] - 1s 219us/sample - loss: 18.4662 - acc: 0.9983
Epoch 93/100
2300/2300 [==============================] - 1s 235us/sample - loss: 17.4254 - acc: 0.9987
Epoch 94/100
2300/2300 [==============================] - 0s 216us/sample - loss: 21.1442 - acc: 0.9987
Epoch 95/100
2300/2300 [==============================] - 0s 212us/sample - loss: 16.7256 - acc: 0.9978
Epoch 96/100
2300/2300 [==============================] - 0s 217us/sample - loss: 22.3610 - acc: 0.9987
Epoch 97/100
2300/2300 [==============================] - 1s 221us/sample - loss: 15.8938 - acc: 0.9983
Epoch 98/100
2300/2300 [==============================] - 0s 209us/sample - loss: 17.8706 - acc: 0.9983
Epoch 99/100
2300/2300 [==============================] - 1s 222us/sample - loss: 16.7062 - acc: 0.9991
Epoch 100/100
2300/2300 [==============================] - 1s 223us/sample - loss: 18.3735 - acc: 0.9978

In [688]:
# model.predict(numpy.array([result.iloc[-20:].to_numpy()]))
VVV =[]
for i in range(1500,2000):
    VVV.append(model.predict(numpy.array([result.iloc[i:i+10].to_numpy()]))[0])
nk = pd.DataFrame(VVV)
# nk = round(nk*8) /8
nk[0] = nk[0]-1072-156
print(nk)
numpy.savetxt("namkang.csv", nk, delimiter=",")

              0          1          2
0      0.631592  68.290970  78.979576
1      1.976807  68.022827  78.428688
2      2.397217  67.892433  78.557892
3      3.735596  68.030510  78.743393
4      4.012329  66.908051  78.883476
..          ...        ...        ...
495  655.805176  65.320961  79.950912
496  656.456299  65.199829  80.253174
497  657.524292  64.946304  79.992455
498  658.885498  65.586479  80.221413
499  660.003540  65.871796  80.250160

[500 rows x 3 columns]

In [689]:
from midiutil import MIDIFile

degrees  = [60, 62, 64, 65, 67, 69, 71, 72]  # MIDI note number
track    = 0
channel  = 0
time     = 0    # In beats
duration = 0.5    # In beats
tempo    = 1  # In BPM
volume   = 100  # 0-127, as per the MIDI standard

MyMIDI = MIDIFile(1)  # One track, defaults to format 1 (tempo track is created
                      # automatically)
MyMIDI.addTempo(track, time, tempo)

for k  in nk.iterrows():
    print(k[0])
    MyMIDI.addNote(track, channel, int(round(k[1][1])), float(k[1][0]), 0.5, int(round(k[1][2])))

with open("major-scale7778.mid", "wb") as output_file:
    MyMIDI.writeFile(output_file)
print("A")

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
A